[build]
  command = 'npm run build'
  publish = '.next'

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200


[context.deploy-preview.edge_functions]
    path = '/*'
    function = 'edge-protection'

[context.branch-deploy.edge_functions]
    path = '/*'
    function = 'edge-protection'